# Generated by Django 4.1.6 on 2023-02-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_logic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$Z6NHVs4dzOzR06knDhSB2l$UPzRlNlyZeYSXVLVKKLjATFI0PuHRNt7SgdkepK+1cQ=', max_length=128),
        ),
    ]
